### DISCUSSION TITLE
Settings generator

### DISCUSSION THREAD

**Discussion by AbdelkaderBah** [spatie/laravel-settings#175] [Ideas]
I am thinking (And willing to work on a pull request) of a settings generator that might be very useful, I will try to explain it here.

## File-based settings template

- A developer can have a YAML or .txt or JSON... etc file where he will describe the settings structure

```YML
path: '/app/Settings/'
general:
  site_name: string
  maintenance: bool
  access:
    - type: bool
    - default: true
permissions:
  admin:
    - _reserved_type: many
    - edit:
        - index: bool
  manager:
    - update: '/Some/Class'
```

## Then execute a command

a laravel command ```laravel-settings:generate```

## Example of generated code

```PHP
class General  extends Settings {
  public string $site_name;
  public bool $maintenance;
  public bool $access = true;

  static group(): string {
       return 'General';
  }
}
```

```PHP
class Permissions  extends Settings {
  public string $site_name;
  public bool $maintenance;
  public bool $access = true;

  static group(): string {
       return 'General';
  }
}

$userType = 'admin'
// Many::class
(new Permission)->of($userType)
    ->node('edit')->value()

$userType = 'manager'
(new Permission)->of($userType)
    // /Some/Class::class
    ->node('update')
    ->set(['a' => 'b'])
```

## Other ideas related

- Maybe add a Transformer, Parser... which can allow something like generating ```.vue``` files for frontend, etc.
